const recipe = [
    {
        "uuid":"5ebf4731-98ef-40cc-ba65-5dca008c35ab",
        "customer-uuid":"8e1fc598-2d58-4ae9-b4cc-62364a0c6ce3",
        "name":"Superfood salad",
        "original-name":"Superfood salad",
        "description":"Full of great veggies and high-fibre quinoa, this easy-to-make salad is nutritious, delicious and super-satisfying. Top with juicy pomegranate seeds for a great burst of flavour.",
        "original-description":"Full of great veggies and high-fibre quinoa, this easy-to-make salad is nutritious, delicious and super-satisfying. Top with juicy pomegranate seeds for a great burst of flavour.",
        "images":[
            "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1460_1_1436891540.jpg",
        ],
        "new-images":[
            {
                "width":800,
                "height":1066,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":229276,
                "url":"https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1460_1_1436891540.jpg?tr=w-800,h-1066",
            },
            {
                "width":806,
                "height":442,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":66579,
                "url":"https://img.jamieoliver.com/home/wp-content/uploads/2015/05/3-67_Superfood-Salad_Jamie-Oliver-Jim-Chapman_SYN-Thumbnail_806x442.jpg",
            },
            {
                "width":310,
                "height":414,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":51140,
                "url":"https://cdn.jamieoliver.com/recipe-database/oldImages/medium/1460_1_1436891540.jpg",
            },
            {
                "width":140,
                "height":187,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":13968,
                "url":"https://img.jamieoliver.com/jamieoliver/recipe-database/66676214.jpg?tr=w-140",
            }
        ],
        "new-original-images":[
            {
                "width":800,
                "height":1066,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":229276,
                "url":"https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1460_1_1436891540.jpg?tr=w-800,h-1066",
            },
            {
                "width":806,
                "height":442,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":66579,
                "url":"https://img.jamieoliver.com/home/wp-content/uploads/2015/05/3-67_Superfood-Salad_Jamie-Oliver-Jim-Chapman_SYN-Thumbnail_806x442.jpg",
            },
            {
                "width":310,
                "height":414,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":51140,
                "url":"https://cdn.jamieoliver.com/recipe-database/oldImages/medium/1460_1_1436891540.jpg",
            },
            {
                "width":140,
                "height":187,
                "type":"jpg",
                "mime":"image/jpeg",
                "wUnits":"px",
                "hUnits":"px",
                "length":13968,
                "url":"https://img.jamieoliver.com/jamieoliver/recipe-database/66676214.jpg?tr=w-140"
            }
        ],
        "ingredients": [
            "2 sweet potatoes (350g each)",
            "1 pinch of dried chilli flakes",
            "1 pinch of ground coriander",
            "1 small pinch of ground cinnamon",
            "olive oil",
            "200 g quinoa",
            "320 g broccoli",
            "35 g mixed nuts such as walnuts, almonds, Brazils",
            "1 pomegranate",
            "extra virgin olive oil",
            "1 splash of balsamic vinegar",
            "2 limes",
            "40 g mixed sprouts",
            "1 punnet of salad cress (use a mixture of varieties, if possible)",
            "1 bunch of fresh coriander (30g)",
            "1 fresh red chilli",
            "1 ripe avocado",
            "20 g feta cheese",
        ],
        "original-ingredients":[
            "2 sweet potatoes (350g each)",
            "1 pinch of dried chilli flakes",
            "1 pinch of ground coriander",
            "1 small pinch of ground cinnamon",
            "olive oil",
            "200 g quinoa",
            "320 g broccoli",
            "35 g mixed nuts such as walnuts, almonds, Brazils",
            "1 pomegranate",
            "extra virgin olive oil",
            "1 splash of balsamic vinegar",
            "2 limes",
            "40 g mixed sprouts",
            "1 punnet of salad cress (use a mixture of varieties, if possible)",
            "1 bunch of fresh coriander (30g)",
            "1 fresh red chilli",
            "1 ripe avocado",
            "20 g feta cheese",
        ],
        "instructions":[
                    "Preheat the oven to 200°C/400°F/gas 6.",
                    "Scrub and chop the sweet potatoes into 2.5cm chunks. Place into a roasting tray with the chilli flakes, ground coriander and cinnamon, a drizzle of olive oil and a little sea salt and black pepper, then toss well.",
                    "Spread out into an even layer and place in the hot oven for 15 to 20 minutes, or until golden and crisp.",
                    "Meanwhile, cook the quinoa in boiling salted water according to the packet instructions.",
                    "Slice the broccoli into small florets, then halve and finely slice the stalk. Place into a heatproof colander and rest it over the quinoa pan. Cover and steam for 3 minutes, or until just tender.",
                    "Once cooked, drain and rinse the quinoa under cold running water, then leave to cool along with the broccoli. Remove the sweet potato from the oven and leave it to cool, too.",
                    "Meanwhile, toast the nuts in a dry frying pan over a medium-high heat for 2 to 3 minutes, then transfer to a pestle and mortar and crush lightly.",
                    "Halve the pomegranate and squeeze half the juice into a large bowl. Add 3 times as much extra virgin olive oil, the lime juice and balsamic vinegar. Whisk well and season to taste.",
                    "Add the cooled broccoli and sprouts to the dressing, then snip in the cress. Roughly chop the coriander (stalks and all), finely slice the chilli and add to the bowl along with the quinoa and sweet potato.",
                    "Toss well, spread out on a serving platter, then scoop out and dot over the avocado flesh.",
                    "Bash the reserved pomegranate half with a wooden spoon so the seeds come tumbling out and scatter these over the platter along with the nuts, snip the cress on top, then serve with the feta crumbled over the top.",
        ],
        "original-instructions":[
            {
                "steps":[
                    "Preheat the oven to 200°C/400°F/gas 6.",
                    "Scrub and chop the sweet potatoes into 2.5cm chunks. Place into a roasting tray with the chilli flakes, ground coriander and cinnamon, a drizzle of olive oil and a little sea salt and black pepper, then toss well.",
                    "Spread out into an even layer and place in the hot oven for 15 to 20 minutes, or until golden and crisp.",
                    "Meanwhile, cook the quinoa in boiling salted water according to the packet instructions.",
                    "Slice the broccoli into small florets, then halve and finely slice the stalk. Place into a heatproof colander and rest it over the quinoa pan. Cover and steam for 3 minutes, or until just tender.",
                    "Once cooked, drain and rinse the quinoa under cold running water, then leave to cool along with the broccoli. Remove the sweet potato from the oven and leave it to cool, too.",
                    "Meanwhile, toast the nuts in a dry frying pan over a medium-high heat for 2 to 3 minutes, then transfer to a pestle and mortar and crush lightly.",
                    "Halve the pomegranate and squeeze half the juice into a large bowl. Add 3 times as much extra virgin olive oil, the lime juice and balsamic vinegar. Whisk well and season to taste.",
                    "Add the cooled broccoli and sprouts to the dressing, then snip in the cress. Roughly chop the coriander (stalks and all), finely slice the chilli and add to the bowl along with the quinoa and sweet potato.",
                    "Toss well, spread out on a serving platter, then scoop out and dot over the avocado flesh.",
                    "Bash the reserved pomegranate half with a wooden spoon so the seeds come tumbling out and scatter these over the platter along with the nuts, snip the cress on top, then serve with the feta crumbled over the top.",
                ],
            },
        ],
        "yield":"6",
        "original-yield":"6",
        "prep-time":"",
        "cook-time":"",
        "total-time":"PT40M",
        "original-total-time":"PT40M",
        "url":"https://www.jamieoliver.com/recipes/vegetables-recipes/superfood-salad/",
        "created":"2020-12-14T00:36:28.863015+00:00",
        "created-by":"RapidAPI",
        "updated":"2020-12-14T00:36:28.863015+00:00",
    },
    { 
        "cook-time": "",
        "created": "2020-12-14T03:48:47.602613+00:00",
        "created-by": "RapidAPI",
        "customer-uuid": "8e1fc598-2d58-4ae9-b4cc-62364a0c6ce3",
        "description": "Cell Regenerator: Chickpeas are an excellent source of protein, vitamin B6 and folate, which is also known as vitamin B9 or folic acid. Just 1 serving of our falafel sandwich provides almost half of your daily value of folate, a key player in building blocks of DNA and RNA, which are essential for rapidly growing tissues (like those of a developing fetus) and rapidly regenerating cells (like red blood cells and immune cells).",
        "images": 
            ["https://www.cleaneatingmag.com/wp-content/uploads/sites/7/2015/11/falafelpitasandwich.jpg", 
            "https://www.cleaneatingmag.com/wp-content/uploads/sites/7/2015/11/falafelpitasandwich.jpg", 
            "https://www.cleaneatingmag.com/wp-content/uploads/sites/7/2015/11/falafelpitasandwich.jpg",
        ],
        "ingredients": [
            "1 15-oz BPA-free can unsalted chickpeas, u2028drained and rinsed",
            "1/4 yellow onion, cut into 3 or 4 chunks", 
            "1/4 cup whole-wheat pastry flour", 
            "2 tbsp fresh flat-leaf parsley", 
            "4 cloves garlic, divided (NOTE: Leave 2 cloves whole and mince 2 cloves.)", 
            "1 tsp sodium-free baking powder", 
            "1/2 tsp ground cumin (TRY: Simply Organic Ground Cumin)", 
            "1/2 tsp ground coriander (TRY: Simply Organic Coriander)", 
            "1/2 tsp sea salt", 
            "Olive oil cooking spray", 
            "1/4 cup tahini paste", 
            "2 tbsp fresh lemon juice", 
            "1/4 tsp paprika (TRY: Simply Organic Paprika)", 
            "6 6-inch whole-wheat pitas", 
            "1 head green leaf or red leaf lettuce, u2028 coarsely shredded", 
            "1 tomato, cut into thin wedges", 
            "1/2 cucumber, peeled and sliced", 
            "1 low-sodium dill pickle, sliced", 
            "1/4 small red onion, thinly sliced", 
            "Harissa or other hot sauce, optional"
        ],
        "instructions": [
            "To a food processor, add chickpeas, yellow onion, flour, parsley, whole garlic, baking powder, cumin, coriander and salt and pulse to a grainy paste, scraping down bowl as necessary. With lightly moistened hands, shape paste into 12 golf ball-size rounds, arranging on a plate.",
            "Coat a very large nonstick skillet with cooking spray and heat on medium-low. Working in batches if necessary to avoid crowding the skillet, add balls and use a spatula to flatten to about ½ inch thick. Cook until browned on bottom, 4 to 5 minutes. Flip and brown other side, 4 to 5 minutes.",
            "Meanwhile, in a small bowl, whisk together tahini, ¼ cup water, lemon juice, remaining minced garlic and paprika.",
            "Cut about 1 inch off top of each pita, forming a pocket. Add 2 falafel to each pita and divide lettuce, tomato, cucumber, pickle, red onion and tahini sauce among pitas. Drizzle each with harissa (if using).",

        ],
        "name": "Falafel Pita Sandwiches with Tahini Sauce",
        "new-images": [{
            "hUnits": "px",
            "height": 576,
            "length": 661565,
            "mime": "image/jpeg",
            "type": "jpg",
            "url": "https://www.cleaneatingmag.com/wp-content/uploads/sites/7/2015/11/falafelpitasandwich.jpg?resize=1024,576",
            "wUnits": "px",
            "width": 1024,
        }],
        "new-original-images": [{
            "hUnits": "px",
            "height": 576,
            "length": 661565,
            "mime": "image/jpeg",
            "type": "jpg",
            "url": "https://www.cleaneatingmag.com/wp-content/uploads/sites/7/2015/11/falafelpitasandwich.jpg?resize=1024,576",
            "wUnits": "px",
            "width": 1024,
        }],
        "original-description": "Cell Regenerator: Chickpeas are an excellent source of protein, vitamin B6 and folate, which is also known as vitamin B9 or folic acid. Just 1 serving of our falafel sandwich provides almost half of your daily value of folate, a key player in building blocks of DNA and RNA, which are essential for rapidly growing tissues (like those of a developing fetus) and rapidly regenerating cells (like red blood cells and immune cells).",
        "original-ingredients": [
            "1 15-oz BPA-free can unsalted chickpeas, u2028drained and rinsed", 
            "1/4 yellow onion, cut into 3 or 4 chunks", 
            "1/4 cup whole-wheat pastry flour", 
            "2 tbsp fresh flat-leaf parsley", 
            "4 cloves garlic, divided (NOTE: Leave 2 cloves whole and mince 2 cloves.)", 
            "1 tsp sodium-free baking powder", 
            "1/2 tsp ground cumin (TRY: Simply Organic Ground Cumin)", 
            "1/2 tsp ground coriander (TRY: Simply Organic Coriander)", 
            "1/2 tsp sea salt", 
            "Olive oil cooking spray", 
            "1/4 cup tahini paste", 
            "2 tbsp fresh lemon juice", 
            "1/4 tsp paprika (TRY: Simply Organic Paprika)", 
            "6 6-inch whole-wheat pitas", 
            "1 head green leaf or red leaf lettuce, u2028 coarsely shredded", 
            "1 tomato, cut into thin wedges", 
            "1/2 cucumber, peeled and sliced", 
            "1 low-sodium dill pickle, sliced", 
            "1/4 small red onion, thinly sliced", 
            "Harissa or other hot sauce, optional",
        ],
        "original-instructions": [
            "To a food processor, add chickpeas, yellow onion, flour, parsley, whole garlic, baking powder, cumin, coriander and salt and pulse to a grainy paste, scraping down bowl as necessary. With lightly moistened hands, shape paste into 12 golf ball-size rounds, arranging on a plate.",
            "Coat a very large nonstick skillet with cooking spray and heat on medium-low. Working in batches if necessary to avoid crowding the skillet, add balls and use a spatula to flatten to about ½ inch thick. Cook until browned on bottom, 4 to 5 minutes. Flip and brown other side, 4 to 5 minutes.",
            "Meanwhile, in a small bowl, whisk together tahini, ¼ cup water, lemon juice, remaining minced garlic and paprika.",
            "Cut about 1 inch off top of each pita, forming a pocket. Add 2 falafel to each pita and divide lettuce, tomato, cucumber, pickle, red onion and tahini sauce among pitas. Drizzle each with harissa (if using).",
        ],
        "original-name": "Falafel Pita Sandwiches with Tahini Sauce",
        "original-prep-time": "PT30M",
        "original-total-time": "PT30M",
        "original-yield": "6",
        "prep-time": "PT30M",
        "total-time": "PT30M",
        "updated": "2020-12-14T03:48:47.602613+00:00",
        "url": "https://www.cleaneatingmag.com/recipes/falafel-pita-sandwiches-with-tahini-sauce/",
        "uuid": "fe8832e7-4ff1-462d-b979-8146ea6089b5",
        "yield": "6",
    }
];

export default recipe;